# Generated by Django 2.0.3 on 2022-01-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
