# Generated by Django 2.0.3 on 2022-02-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220130_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='parties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('party_name', models.CharField(max_length=100)),
                ('party_sign', models.CharField(max_length=100)),
                ('party_image', models.ImageField(default='', upload_to='students/')),
            ],
            options={
                'db_table': 'parties',
            },
        ),
    ]
