# Generated by Django 2.0.3 on 2022-02-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_parties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='party_image',
            field=models.ImageField(default='', upload_to='vote_image/'),
        ),
    ]
