# Generated by Django 2.0.3 on 2022-02-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220201_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='vote_box',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parties')),
                ('voter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.voter')),
            ],
            options={
                'db_table': 'vote_box',
            },
        ),
    ]
