# Generated by Django 2.0.3 on 2022-02-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_vote_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote_box',
            name='vote_id',
            field=models.ForeignKey(on_delete=None, to='myapp.parties'),
        ),
        migrations.AlterField(
            model_name='vote_box',
            name='voter_id',
            field=models.ForeignKey(on_delete=None, to='myapp.voter'),
        ),
    ]
